#!/bin/sh

# Source the INSTALL_DIRECTORY variable
[ -f ~/profile ] && . ~/profile


cat > ~/run <<EOF
#!/bin/bash
if ps -aux | grep -v grep | grep ts3server_linux; then
        echo "Error"
else
        exec /usr/bin/screen -AmdS TS3Server $TEAMSPEAK_DIR/ts3server_minimal_runscript.sh default_voice_port=$PORT_TS3 &
	sleep 10
	if [ ! -f "privilege_key" ]; then
		touch privilege_key
		grep -h token= /home/dotcloud/teamspeak/logs/* >> privilege_key
	fi
fi
EOF
chmod +x ~/run

echo
echo
echo "########################################################"
echo The address for TeamSpeak clients is : "$DOTCLOUD_TS3_TS3_HOST":"$DOTCLOUD_TS3_TS3_PORT" 
echo "########################################################"
echo
echo
echo The address for TeamSpeak clients is : "DOTCLOUD_TS3_TS3_HOST":"$DOTCLOUD_TS3_TS3_HOST" >> ~/IP_TS3_SERVER
