#!/bin/sh

# Source the INSTALL_DIRECTORY variable
[ -f ~/profile ] && . ~/profile


cat > ~/run <<EOF
#!/bin/bash
if ps -aux | grep -v grep | grep ts3server_linux; then
        echo "Error"
else
        exec /usr/bin/screen -AmdS TS3Server $TEAMSPEAK_DIR/ts3server_minimal_runscript.sh default_voice_port=$PORT_TS3 &
	sleep 2
	if [ ! -f "privilege_key" ]; then
		echo -n "The privilege key for your TeamSpeak Server is : " > privilege_key
		grep -h token= ~/teamspeak/logs/* | cut -d= -f2 >> privilege_key
	fi
fi
EOF
chmod +x ~/run

echo
echo
echo "########################################################"
echo The address for TeamSpeak clients is : "$DOTCLOUD_TS3_TS3_HOST":"$DOTCLOUD_TS3_TS3_PORT" 
echo "########################################################"
echo
echo
echo "\033[01mTo have you privilege key, please use this command : \"dotcloud run $DOTCLOUD_PROJECT.ts3 cat prilege_key\"\033[00m"
echo The address for TeamSpeak clients is : "DOTCLOUD_TS3_TS3_HOST":"$DOTCLOUD_TS3_TS3_HOST" >> ~/IP_TS3_SERVER
